name: Build latest image

on:
  push:
    branches:
    - master

env:
  IMAGE_NAME: loranmutafov/simple-bastion:latest

jobs:
  build:
    name: Build and push :latest to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: DOCKER_BUILDKIT=1 docker build . -t $IMAGE_NAME

    - name: Push Docker image
      run: docker push $IMAGE_NAME
